# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dead Rooster
lang: fr
timezone: Europe/Paris
repository:
  url: https://github.com/dirtyhenry/dead-rooster-articles
  name: articles
permalink: /:title/
description: >- # this means to ignore newlines until "baseurl:"
  Surtout du rock, des films, du foot et de la pop culture.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.deadrooster.org" # the base hostname & protocol for your site, e.g. http://example.com
markdown: CommonMark
port: 4001

# Build settings
theme: kids
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap

jekyll-archives:
  enabled: ["categories", "tags"]
  layout: archive
  slug_mode: latin
  permalinks:
    tag: "/tag/:name/"
    category: "/category/:name/"

kids:
  archives_path: "archives/"
  # A boolean indicating if the site contains an Apple touch icon file
  apple_touch_icon: false
  # The maximal number of posts featured on the home
  home_posts: 20
  # A boolean indicating if the site contains a `site.webmanifest` file
  webmanifest: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Makefile
  - package.json
  - package-lock.json
  - README.md
  - stack.yml
  - webpack.config.js
